import { NextRequest, NextResponse } from 'next/server';
import { withRole } from '../../../../middleware';
import type { AuthContext } from '../../../../middleware/auth';
import { getAssignmentById, updateAssignment, deleteAssignment } from '../../../../lib/server/assignments';
import { getDb } from '../../../../lib/db';
import { z } from 'zod';

const UpdateAssignmentSchema = z.object({
  title: z.string().min(1).optional(),
  description: z.string().optional(),
  slideAssetVersionId: z.string().nullable().optional(),
  quizAssetVersionId: z.string().nullable().optional(),
  releaseAt: z.string().nullable().optional(),
  dueAt: z.string().nullable().optional(),
  status: z.enum(['draft', 'scheduled', 'released', 'closed']).optional()
});

// GET /api/teacher/assignments/[assignmentId] - Get single assignment
export const GET = withRole(['teacher'], async (req: NextRequest, ctx: AuthContext, routeCtx: { params: Promise<Record<string, string>> }) => {
  const { assignmentId } = await routeCtx.params;

  const assignment = await getAssignmentById(assignmentId);

  if (!assignment) {
    return NextResponse.json({ error: 'Assignment not found' }, { status: 404 });
  }

  if (assignment.teacher_id !== ctx.user.id) {
    return NextResponse.json({ error: 'Access denied' }, { status: 403 });
  }

  // Fetch asset to get OpenMAIC URL for slides
  // The version's payload_json contains openmaicClassroomId if generated by OpenMAIC
  let slideOpenmaicUrl: string | null = null;
  let quizOpenmaicUrl: string | null = null;

  const db = getDb();

  if (assignment.slide_asset_version_id) {
    const versionResult = await db.query(`
      SELECT payload_json FROM content_asset_versions WHERE id = $1
    `, [assignment.slide_asset_version_id]);
    const version = versionResult.rows[0] as { payload_json: string } | undefined;

    if (version?.payload_json && version.payload_json.trim()) {
      try {
        const payload = JSON.parse(version.payload_json);
        if (payload.openmaicClassroomId) {
          const baseUrl = process.env.OPENMAIC_PUBLIC_URL || process.env.OPENMAIC_BASE_URL || 'http://localhost:3002';
          slideOpenmaicUrl = `${baseUrl}/classroom/${payload.openmaicClassroomId}`;
        }
      } catch {
        // ignore parse errors
      }
    }
  }

  if (assignment.quiz_asset_version_id) {
    const versionResult = await db.query(`
      SELECT payload_json FROM content_asset_versions WHERE id = $1
    `, [assignment.quiz_asset_version_id]);
    const version = versionResult.rows[0] as { payload_json: string } | undefined;

    if (version?.payload_json && version.payload_json.trim()) {
      try {
        const payload = JSON.parse(version.payload_json);
        if (payload.openmaicClassroomId) {
          const baseUrl = process.env.OPENMAIC_PUBLIC_URL || process.env.OPENMAIC_BASE_URL || 'http://localhost:3002';
          quizOpenmaicUrl = `${baseUrl}/classroom/${payload.openmaicClassroomId}`;
        }
      } catch {
        // ignore parse errors
      }
    }
  }

  return NextResponse.json({
    assignment: {
      ...assignment,
      slideOpenmaicUrl,
      quizOpenmaicUrl
    }
  });
});

// PATCH /api/teacher/assignments/[assignmentId] - Update assignment
export const PATCH = withRole(['teacher'], async (req: NextRequest, ctx: AuthContext, routeCtx: { params: Promise<Record<string, string>> }) => {
  const { assignmentId } = await routeCtx.params;

  const assignment = await getAssignmentById(assignmentId);
  if (!assignment) {
    return NextResponse.json({ error: 'Assignment not found' }, { status: 404 });
  }

  if (assignment.teacher_id !== ctx.user.id) {
    return NextResponse.json({ error: 'Access denied' }, { status: 403 });
  }

  const body = await req.json();
  const parsed = UpdateAssignmentSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.issues }, { status: 400 });
  }

  const updateData = {
    title: parsed.data.title,
    description: parsed.data.description,
    slideAssetVersionId: parsed.data.slideAssetVersionId ?? undefined,
    quizAssetVersionId: parsed.data.quizAssetVersionId ?? undefined,
    releaseAt: parsed.data.releaseAt ?? undefined,
    dueAt: parsed.data.dueAt ?? undefined,
    status: parsed.data.status
  };

  try {
    const updated = await updateAssignment(assignmentId, updateData);
    if (!updated) {
      return NextResponse.json({ error: 'Assignment not found' }, { status: 404 });
    }
    return NextResponse.json({ assignment: updated });
  } catch (error) {
    if (error instanceof Error) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }
    return NextResponse.json({ error: 'Failed to update assignment' }, { status: 500 });
  }
});

// DELETE /api/teacher/assignments/[assignmentId] - Delete assignment
export const DELETE = withRole(['teacher'], async (req: NextRequest, ctx: AuthContext, routeCtx: { params: Promise<Record<string, string>> }) => {
  const { assignmentId } = await routeCtx.params;

  const assignment = await getAssignmentById(assignmentId);
  if (!assignment) {
    return NextResponse.json({ error: 'Assignment not found' }, { status: 404 });
  }

  if (assignment.teacher_id !== ctx.user.id) {
    return NextResponse.json({ error: 'Access denied' }, { status: 403 });
  }

  try {
    await deleteAssignment(assignmentId);
    return new NextResponse(null, { status: 204 });
  } catch (error) {
    if (error instanceof Error) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }
    return NextResponse.json({ error: 'Failed to delete assignment' }, { status: 500 });
  }
});
